apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: userregistration
  name: userregistration
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userregistration
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userregistration
    spec:
      containers:
      - image: image_to_deploy
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3030
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: userregistration
  namespace: application
  labels:
    run: userregistration
spec:
  ports:
  - port: 3030
    protocol: TCP
  selector:
    app: userregistration
  type: ClusterIP
 
